In [2]:
import numpy as np
import pandas as pd

In [252]:
# df1 = pd.read_csv('test400_outputs.csv')
# df2 = pd.read_csv('test59_outputs.csv')
# df = pd.concat([df1, df2], ignore_index=True)
df = pd.read_csv('test1110_outputs.csv')
df.head()
df.shape

(1089, 9)

In [246]:
df['race'].unique()

array(['Black', 'White', 'Middle Eastern', 'Southeast Asian', 'Indian',
       'Latino_Hispanic', 'East Asian'], dtype=object)

In [240]:
df['race4'].unique()

array(['Black', 'White', 'Asian', 'Indian'], dtype=object)

In [247]:
mapping1 = {'East Asian': 0, 'Latino_Hispanic': 1, 'Southeast Asian': 2, 'White': 3,
       'Black': 4, 'Middle Eastern': 5}
df['race_ind'] = df['race'].map(mapping1)

mapping2 = {'Asian': 0, 'Black': 1, 'White': 2, 'Indian': 3}
df['race4_ind'] = df['race4'].map(mapping2)

mappingComp = {0: 0, 1: 5, 2: 2, 3: 3, 4: 4, 5: 5} #to get accuracy, maps Middle Eastern and Latino_Hispanic to same id
df['ethnicity_comp'] = df['race_ind'].map(mappingComp)

clean_filename = lambda x: x.replace("detected_faces/", "").replace("_face0.jpg", "")
df['img_name_clean'] = df['face_name_align'].apply(clean_filename)
df.head(70)

,face_name_align,race,race4,gender,age,race_scores_fair,race_scores_fair_4,gender_scores_fair,age_scores_fair,race_ind,race4_ind,ethnicity_comp,img_name_clean
0,detected_faces/20170120223029947_face0.jpg,Black,Black,Male,50-59,[3.9074174e-03 9.5537513e-01 9.2430990e-03 8.9...,[0.0021265 0.99367213 0.0019878 0.00221359],[0.99625224 0.00374778],[1.4868459e-04 4.0584229e-04 3.2125369e-03 1.3...,4.0,1,4.0,20170120223029947
1,detected_faces/20170120224525249_face0.jpg,White,White,Male,50-59,[8.6085802e-01 1.4881747e-03 1.5367202e-02 1.7...,[0.9004365 0.00849881 0.09001411 0.00105061],[9.993261e-01 6.738520e-04],[2.2302384e-05 1.4561992e-05 2.8126669e-04 5.7...,3.0,2,3.0,20170120224525249
2,detected_faces/20170120134446448_face0.jpg,White,White,Male,70+,[9.8004025e-01 3.3774359e-05 1.9209686e-04 5.8...,[9.9016881e-01 1.4497693e-04 9.5288558e-03 1.5...,[0.90577155 0.09422841],[0.00101653 0.00199681 0.01000107 0.0492616 0...,3.0,2,3.0,20170120134446448
3,detected_faces/20170120133547085_face0.jpg,White,White,Male,30-39,[9.8463184e-01 2.0135265e-04 2.2371004e-03 1.1...,[9.9866831e-01 8.6886645e-04 1.6977331e-04 2.9...,[0.9983214 0.00167858],[2.2225533e-06 3.8783390e-05 4.6113641e-03 3.5...,3.0,2,3.0,20170120133547085
4,detected_faces/20170120225003182_face0.jpg,White,White,Female,30-39,[9.9805743e-01 3.6794925e-05 2.4860192e-04 1.6...,[9.9858278e-01 8.8393994e-05 1.0197954e-03 3.0...,[0.05994049 0.9400595 ],[1.4541771e-04 1.7752905e-03 1.7033836e-02 2.4...,3.0,2,3.0,20170120225003182
...,...,...,...,...,...,...,...,...,...,...,...,...,...
65,detected_faces/20170120223924629_face0.jpg,White,White,Male,30-39,[0.515517 0.00089439 0.37469926 0.00529504 0...,[9.9378484e-01 6.3246029e-04 4.0606698e-03 1.5...,[0.9341464 0.06585364],[4.3844688e-05 4.2865309e-04 1.0658791e-02 7.2...,3.0,2,3.0,20170120223924629
66,detected_faces/20170120222630481_face0.jpg,White,White,Female,30-39,[0.6900547 0.01035381 0.1689056 0.01224346 0...,[0.9869361 0.00520681 0.00638176 0.00147535],[0.04612538 0.9538746 ],[1.97070898e-04 5.82472747e-03 3.64200398e-02 ...,3.0,2,3.0,20170120222630481
67,detected_faces/20170120224044694_face0.jpg,White,White,Male,50-59,[9.2944628e-01 2.3786912e-05 2.0997929e-03 3.6...,[9.9900067e-01 7.4251402e-05 1.5945900e-04 7.6...,[9.9931246e-01 6.8752741e-04],[5.8098308e-06 5.5053765e-06 1.6841326e-04 8.0...,3.0,2,3.0,20170120224044694
68,detected_faces/20170120230335947_face0.jpg,White,White,Female,50-59,[8.8264757e-01 8.1019127e-04 4.5028478e-02 2.5...,[9.4687384e-01 7.7012030e-04 5.2124225e-02 2.3...,[0.02273447 0.9772655 ],[1.5067770e-04 1.6279176e-03 7.2266469e-03 1.2...,3.0,2,3.0,20170120230335947
69,detected_faces/201701161846515488_face0.jpg,East Asian,Asian,Female,20-29,[1.3517655e-02 4.7793626e-05 2.3374483e-03 9.5...,[8.8813938e-03 2.0823329e-04 9.9076748e-01 1.4...,[5.7922775e-04 9.9942076e-01],[1.9927479e-07 4.9763810e-05 2.4803990e-02 7.5...,0.0,0,0.0,201701161846515488

In [134]:
#dataset: https://www.kaggle.com/datasets/nipunarora8/age-gender-and-ethnicity-face-data-csv
#0 to 4, denoting White, Black, Asian, Indian, and Others (like Hispanic, Latino, Middle Eastern)

trueY_df = pd.read_csv('/Users/makenarobison/Desktop/Computer Vision Research/age_gender.csv')

trueY_df.head()

,age,ethnicity,gender,img_name,pixels
0,1,2,0,20161219203650636.jpg.chip.jpg,129 128 128 126 127 130 133 135 139 142 145 14...
1,1,2,0,20161219222752047.jpg.chip.jpg,164 74 111 168 169 171 175 182 184 188 193 199...
2,1,2,0,20161219222832191.jpg.chip.jpg,67 70 71 70 69 67 70 79 90 103 116 132 145 155...
3,1,2,0,20161220144911423.jpg.chip.jpg,193 197 198 200 199 200 202 203 204 205 208 21...
4,1,2,0,20161220144914327.jpg.chip.jpg,202 205 209 210 209 209 210 211 212 214 218 21...

In [248]:
# ethinicity key: 0 to 4, denoting White, Black, Asian, Indian, and Others (like Hispanic, Latino, Middle Eastern)

mapping3 = {0: 3, 1: 4, 2: 0, 3: 2, 4: 5}
trueY_df['ethnicity_comp_true'] = trueY_df['ethnicity'].map(mapping3)

clean_filename = lambda x: x.replace(".jpg.chip.jpg", "")
trueY_df['img_name_clean'] = trueY_df['img_name'].apply(clean_filename)

trueY_df.head()

,age,ethnicity,gender,img_name,pixels,ethnicity_comp_true,img_name_clean
0,1,2,0,20161219203650636.jpg.chip.jpg,129 128 128 126 127 130 133 135 139 142 145 14...,0,20161219203650636
1,1,2,0,20161219222752047.jpg.chip.jpg,164 74 111 168 169 171 175 182 184 188 193 199...,0,20161219222752047
2,1,2,0,20161219222832191.jpg.chip.jpg,67 70 71 70 69 67 70 79 90 103 116 132 145 155...,0,20161219222832191
3,1,2,0,20161220144911423.jpg.chip.jpg,193 197 198 200 199 200 202 203 204 205 208 21...,0,20161220144911423
4,1,2,0,20161220144914327.jpg.chip.jpg,202 205 209 210 209 209 210 211 212 214 218 21...,0,20161220144914327

In [249]:
#accuracy comparison
print(df.shape)
print(trueY_df.shape)
merged_df = pd.merge(df, trueY_df, on='img_name_clean')
print(merged_df.shape)
# Filter matching IDs
matching_ids_df = merged_df[merged_df['img_name_clean'].notna()]

selected_columns = ['ethnicity', 'ethnicity_comp_true', 'ethnicity_comp']
selected_df = matching_ids_df[selected_columns]

selected_df.head(30)
selected_df.shape

(1089, 13)
(23705, 7)
(1099, 19)

(1099, 3)

In [250]:
true_pred = {0: 0, 2: 0, 3: 0, 4: 0, 5: 0}
error_pred = {0: 0, 2: 0, 3: 0, 4: 0, 5: 0}
total_pred = {0: 0, 2: 0, 3: 0, 4: 0, 5: 0}
error_imgs = []
# Compare columns for matched IDs
for index, row in matching_ids_df.iterrows():
    id_val = row['img_name_clean']
    pred_val = row['ethnicity_comp']
    actual_val = row['ethnicity_comp_true']
    
    total_pred[actual_val] += 1
    # Example comparison logic
    if pred_val == actual_val:
        true_pred[actual_val] += 1
    else:
        error_imgs.append(id_val)
        error_pred[actual_val] += 1

accuracy = sum(true_pred.values()) / sum(total_pred.values())

error = sum(error_pred.values()) / sum(total_pred.values())

#precision = true_pred[1] / (true_pred[1] + error_pred[1])

# Calculate accuracy, error rate, and precision for each class
class_accuracy = {}
class_error_rate = {}
class_precision = {}

for class_val in true_pred.keys():
 if class_val != 1 and total_pred[class_val] > 0: 
        class_accuracy[class_val] = true_pred[class_val] / total_pred[class_val]
        class_error_rate[class_val] = error_pred[class_val] / total_pred[class_val]
        if true_pred[class_val] + error_pred[class_val] > 0:
            class_precision[class_val] = true_pred[class_val] / (true_pred[class_val] + error_pred[class_val])
        else:
            class_precision[class_val] = None

print(true_pred)
print(total_pred)
print(error_pred)
for class_val in true_pred.keys():
   if class_val != 1 and total_pred[class_val] > 0:  # Skip class 1 and check if there are instances of this class
        print(f"Class {class_val}:")
        print(f"  Accuracy: {class_accuracy[class_val]:.2f}")
        print(f"  Error Rate: {class_error_rate[class_val]:.2f}")
        if class_precision[class_val] is not None:
            print(f"  Precision: {class_precision[class_val]:.2f}")
        else:
            print("  Precision: Not calculable (no instances)")

{0: 12, 2: 2, 3: 539, 4: 62, 5: 2}
{0: 20, 2: 402, 3: 587, 4: 80, 5: 10}
{0: 8, 2: 400, 3: 48, 4: 18, 5: 8}
Class 0:
  Accuracy: 0.60
  Error Rate: 0.40
  Precision: 0.60
Class 2:
  Accuracy: 0.00
  Error Rate: 1.00
  Precision: 0.00
Class 3:
  Accuracy: 0.92
  Error Rate: 0.08
  Precision: 0.92
Class 4:
  Accuracy: 0.78
  Error Rate: 0.23
  Precision: 0.78
Class 5:
  Accuracy: 0.20
  Error Rate: 0.80
  Precision: 0.20